### ISSUE TITLE
ValueError: Input image size (128*128) doesn't match model (224*224).

### ISSUE THREAD

**Issue by asharani97** [Extreme-classification/MUFIN#2]
Hello,
 I am getting the above error, if I place images folder in the MM-Amazon dataset folder.
If I go by the instructions, the folder to download via gdown link doesn't have images.bin. So, code gives images.bin not found .
When placed the file getting the above error.

What is the exact problem  here ?
Exact Error : 
'''
f"Input image size ({height}*{width}) doesn't match model ({self.image_size[0]}*{self.image_size[1]})."
ValueError: Input image size (128*128) doesn't match model (224*224).

'''

**Comment by anshumitts** [comment]
Dear @asharani97 , I am not sure what is the error.
Please provide us the following
run tree $HOME/scratch/XC and post the results

**Comment by asharani97** [comment]
Thanks for your reply, below is the results for the command:

/DATA/rani1/scratch/XC/
├── data
│   ├── MM-AmazonTitles-300K
│   │   ├── download_images.ipynb
│   │   ├── filter_labels_test.txt
│   │   ├── filter_labels_train.txt
│   │   ├── images
│   │   │   ├── img.bin
│   │   │   ├── label.img.bin.npz
│   │   │   ├── label.img.uid.txt
│   │   │   ├── test.img.bin.npz
│   │   │   ├── test.img.uid.txt
│   │   │   ├── train.img.bin.npz
│   │   │   └── train.img.uid.txt
│   │   ├── img.urls.txt
│   │   ├── raw_data
│   │   │   ├── label.raw.txt
│   │   │   ├── test.raw.txt
│   │   │   └── train.raw.txt
│   │   ├── sentencebert
│   │   │   ├── label.txt.seq.memmap.dat
│   │   │   ├── label.txt.seq.memmap.meta
│   │   │   ├── test.txt.seq.memmap.dat
│   │   │   ├── test.txt.seq.memmap.meta
│   │   │   ├── train.txt.seq.memmap.dat
│   │   │   └── train.txt.seq.memmap.meta
│   │   ├── trn_X_Y.txt
│   │   └── tst_X_Y.txt
│   └── MM-AmazonTitles-300K.zip
├── models
│   └── MM-AmazonTitles-300K
│       └── MufinMultiModal
│           └── v_MUFIN
│               ├── anns_m1_map.pkl
│               ├── filter_model_MufinXAttnRanker.pkl
│               ├── filter_model.pkl
│               ├── filter_model-warm.pkl
│               ├── model_MufinXAttnRanker.pkl
│               ├── model.pkl
│               ├── model-warm.pkl
│               ├── ova_module.pkl
│               └── part_0
│                   ├── anns_m1.index
│                   └── anns_m1.metadata
├── programs
│   ├── CafeXC
│   │   ├── CafeXC.yml
│   │   ├── get_examples.ipynb
│   │   ├── README.md
│   │   ├── tokenize.ipynb
│   │   └── xc
│   │       ├── libs
│   │       │   ├── anns.py
│   │       │   ├── build_data.py
│   │       │   ├── cluster.py
│   │       │   ├── collate_fn.py
│   │       │   ├── custom_dtypes.py
│   │       │   ├── data_base.py
│   │       │   ├── data_img.py
│   │       │   ├── data_lbl.py
│   │       │   ├── dataloader.py
│   │       │   ├── dataparallel.py
│   │       │   ├── dataset.py
│   │       │   ├── data_shorty.py
│   │       │   ├── data_txt.py
│   │       │   ├── diskann.py
│   │       │   ├── dtypes.py
│   │       │   ├── fast_cluster.py
│   │       │   ├── graph.py
│   │       │   ├── loss.py
│   │       │   ├── model_base.py
│   │       │   ├── model.py
│   │       │   ├── model_utils.py
│   │       │   ├── optimizer_utils.py
│   │       │   ├── parameters.py
│   │       │   ├── __pycache__
│   │       │   │   ├── anns.cpython-36.pyc
│   │       │   │   ├── cluster.cpython-36.pyc
│   │       │   │   ├── custom_dtypes.cpython-36.pyc
│   │       │   │   ├── data_base.cpython-36.pyc
│   │       │   │   ├── data_img.cpython-36.pyc
│   │       │   │   ├── data_img.cpython-39.pyc
│   │       │   │   ├── data_lbl.cpython-36.pyc
│   │       │   │   ├── dataloader.cpython-36.pyc
│   │       │   │   ├── dataparallel.cpython-36.pyc
│   │       │   │   ├── dataset.cpython-36.pyc
│   │       │   │   ├── dataset.cpython-39.pyc
│   │       │   │   ├── data_shorty.cpython-36.pyc
│   │       │   │   ├── data_txt.cpython-36.pyc
│   │       │   │   ├── fast_cluster.cpython-36.pyc
│   │       │   │   ├── loss.cpython-36.pyc
│   │       │   │   ├── model_base.cpython-36.pyc
│   │       │   │   ├── model_utils.cpython-36.pyc
│   │       │   │   ├── optimizer_utils.cpython-36.pyc
│   │       │   │   ├── parameters.cpython-36.pyc
│   │       │   │   ├── parameters.cpython-37.pyc
│   │       │   │   ├── parameters.cpython-39.pyc
│   │       │   │   ├── utils.bin_index-29.py36m.1.nbc
│   │       │   │   ├── utils.bin_index-29.py36m.2.nbc
│   │       │   │   ├── utils.bin_index-29.py36m.nbi
│   │       │   │   ├── utils.bin_index-29.py39.1.nbc
│   │       │   │   ├── utils.bin_index-29.py39.2.nbc
│   │       │   │   ├── utils.bin_index-29.py39.nbi
│   │       │   │   ├── utils.cpython-36.pyc
│   │       │   │   ├── utils.cpython-37.pyc
│   │       │   │   └── utils.cpython-39.pyc
│   │       │   └── utils.py
│   │       ├── method
│   │       │   └── mufin
│   │       │       ├── dataset.py
│   │       │       ├── model.py
│   │       │       ├── models_encoders.py
│   │       │       ├── network.py
│   │       │       └── __pycache__
│   │       │           ├── dataset.cpython-36.pyc
│   │       │           ├── dataset.cpython-39.pyc
│   │       │           ├── model.cpython-36.pyc
│   │       │           ├── model.cpython-39.pyc
│   │       │           ├── models_encoders.cpython-36.pyc
│   │       │           └── network.cpython-36.pyc
│   │       ├── models
│   │       │   ├── custom_transformer.py
│   │       │   ├── models_base.py
│   │       │   ├── models_clf.py
│   │       │   ├── models_emb.py
│   │       │   ├── models_fusion.py
│   │       │   ├── models_img.py
│   │       │   ├── models_txt.py
│   │       │   ├── network.py
│   │       │   └── __pycache__
│   │       │       ├── custom_transformer.cpython-36.pyc
│   │       │       ├── models_base.cpython-36.pyc
│   │       │       ├── models_clf.cpython-36.pyc
│   │       │       ├── models_emb.cpython-36.pyc
│   │       │       ├── models_fusion.cpython-36.pyc
│   │       │       ├── models_img.cpython-36.pyc
│   │       │       ├── models_img.cpython-39.pyc
│   │       │       └── models_txt.cpython-36.pyc
│   │       └── tools
│   │           ├── analysis.py
│   │           ├── evaluate.py
│   │           ├── extract_eval.py
│   │           ├── get_pre_train.py
│   │           ├── label_features_split.py
│   │           ├── __pycache__
│   │           │   └── tokenize_text.cpython-36.pyc
│   │           └── tokenize_text.py
│   ├── MUFIN
│   │   ├── configs
│   │   │   ├── LF-AmazonTitles-131K.json
│   │   │   └── MM-AmazonTitles-300K.json
│   │   ├── img_db_hash.ipynb
│   │   ├── LICENSE
│   │   ├── MUFIN.ipynb
│   │   ├── MUFIN.pdf
│   │   ├── mufin.py
│   │   ├── parameters.py
│   │   ├── __pycache__
│   │   │   ├── parameters.cpython-36.pyc
│   │   │   ├── parameters.cpython-37.pyc
│   │   │   └── parameters.cpython-39.pyc
│   │   ├── README.md
│   │   ├── run_MUFIN.sh
│   │   └── run_pretrained.sh
│   └── pyxclib
│       ├── build
│       │   ├── bdist.linux-x86_64
│       │   ├── lib.linux-x86_64-3.6
│       │   │   └── xclib
│       │   │       ├── classifier
│       │   │       │   ├── base.py
│       │   │       │   ├── __init__.py
│       │   │       │   ├── kcentroid.py
│       │   │       │   ├── knn.py
│       │   │       │   ├── mips.py
│       │   │       │   ├── ova.py
│       │   │       │   ├── parameters_base.py
│       │   │       │   ├── parameters.py
│       │   │       │   ├── slice.py
│       │   │       │   └── _svm.py
│       │   │       ├── data
│       │   │       │   ├── data_loader.py
│       │   │       │   ├── data_statistics.py
│       │   │       │   ├── data_utils.py
│       │   │       │   ├── features.py
│       │   │       │   ├── __init__.py
│       │   │       │   └── labels.py
│       │   │       ├── embeddings
│       │   │       │   ├── fasttext_embeddings.py
│       │   │       │   └── __init__.py
│       │   │       ├── evaluation
│       │   │       │   ├── __init__.py
│       │   │       │   └── xc_metrics.py
│       │   │       ├── __init__.py
│       │   │       └── utils
│       │   │           ├── analysis.py
│       │   │           ├── ann.py
│       │   │           ├── clustering.py
│       │   │           ├── dense.py
│       │   │           ├── graph.py
│       │   │           ├── __init__.py
│       │   │           ├── matrix.py
│       │   │           ├── misc.py
│       │   │           ├── numba_utils.py
│       │   │           ├── shortlist.py
│       │   │           ├── _sparse.c
│       │   │           ├── _sparse.cpython-36m-x86_64-linux-gnu.so
│       │   │           ├── sparse.py
│       │   │           └── text.py
│       │   ├── lib.linux-x86_64-3.9
│       │   │   └── xclib
│       │   │       ├── classifier
│       │   │       │   ├── base.py
│       │   │       │   ├── __init__.py
│       │   │       │   ├── kcentroid.py
│       │   │       │   ├── knn.py
│       │   │       │   ├── mips.py
│       │   │       │   ├── ova.py
│       │   │       │   ├── parameters_base.py
│       │   │       │   ├── parameters.py
│       │   │       │   ├── slice.py
│       │   │       │   └── _svm.py
│       │   │       ├── data
│       │   │       │   ├── data_loader.py
│       │   │       │   ├── data_statistics.py
│       │   │       │   ├── data_utils.py
│       │   │       │   ├── features.py
│       │   │       │   ├── __init__.py
│       │   │       │   └── labels.py
│       │   │       ├── embeddings
│       │   │       │   ├── fasttext_embeddings.py
│       │   │       │   └── __init__.py
│       │   │       ├── evaluation
│       │   │       │   ├── __init__.py
│       │   │       │   └── xc_metrics.py
│       │   │       ├── __init__.py
│       │   │       └── utils
│       │   │           ├── analysis.py
│       │   │           ├── ann.py
│       │   │           ├── clustering.py
│       │   │           ├── dense.py
│       │   │           ├── graph.py
│       │   │           ├── __init__.py
│       │   │           ├── matrix.py
│       │   │           ├── misc.py
│       │   │           ├── numba_utils.py
│       │   │           ├── shortlist.py
│       │   │           ├── _sparse.c
│       │   │           ├── _sparse.cpython-39-x86_64-linux-gnu.so
│       │   │           ├── sparse.py
│       │   │           └── text.py
│       │   ├── temp.linux-x86_64-3.6
│       │   │   └── xclib
│       │   │       └── utils
│       │   │           └── _sparse.o
│       │   └── temp.linux-x86_64-3.9
│       │       └── xclib
│       │           └── utils
│       │               └── _sparse.o
│       ├── dist
│       │   ├── xclib-0.97-py3.6-linux-x86_64.egg
│       │   └── xclib-0.97-py3.9-linux-x86_64.egg
│       ├── LICENSE
│       ├── README.md
│       ├── setup.py
│       ├── xclib
│       │   ├── classifier
│       │   │   ├── base.py
│       │   │   ├── __init__.py
│       │   │   ├── kcentroid.py
│       │   │   ├── knn.py
│       │   │   ├── mips.py
│       │   │   ├── ova.py
│       │   │   ├── parameters_base.py
│       │   │   ├── parameters.py
│       │   │   ├── README.md
│       │   │   ├── slice.py
│       │   │   └── _svm.py
│       │   ├── data
│       │   │   ├── data_loader.py
│       │   │   ├── data_statistics.py
│       │   │   ├── data_utils.py
│       │   │   ├── features.py
│       │   │   ├── __init__.py
│       │   │   └── labels.py
│       │   ├── embeddings
│       │   │   ├── fasttext_embeddings.py
│       │   │   └── __init__.py
│       │   ├── evaluation
│       │   │   ├── __init__.py
│       │   │   └── xc_metrics.py
│       │   ├── examples
│       │   │   ├── compute_features.py
│       │   │   ├── convert_format.pl
│       │   │   ├── decile_wise_analysis.py
│       │   │   ├── evaluate.py
│       │   │   ├── fast_evaluate.py
│       │   │   ├── get_ftx_embeddings.py
│       │   │   ├── run_classifiers.py
│       │   │   ├── run_classifiers.sh
│       │   │   └── sparse_bow_features_from_raw_data.py
│       │   ├── __init__.py
│       │   └── utils
│       │       ├── analysis.py
│       │       ├── ann.py
│       │       ├── clustering.py
│       │       ├── dense.py
│       │       ├── graph.py
│       │       ├── __init__.py
│       │       ├── matrix.py
│       │       ├── misc.py
│       │       ├── numba_utils.py
│       │       ├── shortlist.py
│       │       ├── _sparse.c
│       │       ├── sparse.py
│       │       ├── _sparse.pyx
│       │       └── text.py
│       └── xclib.egg-info
│           ├── dependency_links.txt
│           ├── PKG-INFO
│           ├── requires.txt
│           ├── SOURCES.txt
│           └── top_level.txt
└── results
    └── MM-AmazonTitles-300K
        ├── MufinMultiModal
        │   └── v_MUFIN
        │       ├── log_eval.txt
        │       ├── log_extract.txt
        │       ├── log_predict.txt
        │       ├── log_ranker_MufinXAttnRanker.txt
        │       ├── log_ranker_MufinXAttnRanker.txt.pred
        │       ├── log_train.txt
        │       ├── module1
        │       ├── module2
        │       │   ├── test.npz
        │       │   └── train.npz
        │       ├── module3
        │       │   ├── encoder.pkl
        │       │   ├── label.txt.pretrained.npy
        │       │   ├── label.txt.pretrained.npz
        │       │   ├── test.txt.pretrained.npy
        │       │   ├── test.txt.pretrained.npz
        │       │   ├── train.txt.pretrained.npy
        │       │   └── train.txt.pretrained.npz
        │       └── module4
        │           ├── m2_test_MufinXAttnRanker.npz
        │           └── m4_test_MufinXAttnRanker.npz
        └── PreTrainedMufinMultiModal
            └── v_MUFIN_pretrained
                ├── log_eval.txt
                ├── log_extract.txt
                ├── log_predict.txt
                ├── log_ranker_MufinXAttnRanker.txt
                ├── log_ranker_MufinXAttnRanker.txt.pred
                ├── log_train.txt
                ├── module1
                ├── module2
                │   ├── test.npz
                │   └── train.npz
                ├── module3
                │   ├── encoder.pkl
                │   ├── label.txt.pretrained.npy
                │   ├── label.txt.pretrained.npz
                │   ├── test.txt.pretrained.npy
                │   ├── test.txt.pretrained.npz
                │   ├── train.txt.pretrained.npy
                │   └── train.txt.pretrained.npz
                └── module4
                    ├── m2_test_MufinXAttnRanker.npz
                    └── m4_test_MufinXAttnRanker.npz

71 directories, 299 files

**Comment by anshumitts** [comment]
Apologies for long delays. I was travelling without Internet access. 

Directory structure seems right to me. Can you also share the entire log including the error? 

UPDATE: I saw the mistake in the last commit. I have fixed the issue. (I was able to run code at my end) 
Please do a git pull on CafeXC and try to run the code again. If it runs, close the commit.

**Comment by asharani97** [comment]
Now I am getting some other error. AttributeError: 'NoneType' object has no attribute 'expand'
`
`Traceback (most recent call last):
File "/DATA/rani1/scratch/XC/programs/MUFIN/mufin.py", line 149, in <module>
main(args.params)
File "/DATA/rani1/scratch/XC/programs/MUFIN/mufin.py", line 116, in main
train(model, params)
File "/DATA/rani1/scratch/XC/programs/MUFIN/mufin.py", line 21, in train
lbl_txt=params.lbl_x_txt)
File "/DATA/rani1/scratch/XC/programs/CafeXC/xc/method/mufin/model.py", line 300, in fit
self.train(trn_dset, tst_dset)
File "/DATA/rani1/scratch/XC/programs/CafeXC/xc/method/mufin/model.py", line 233, in train
_ = self.step(trn_dl, epoch)
File "/DATA/rani1/scratch/XC/programs/CafeXC/xc/libs/model_base.py", line 76, in step
output = self.net(batch)
File "/DATA/rani1/miniconda3/envs/xc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/DATA/rani1/scratch/XC/programs/CafeXC/xc/method/mufin/network.py", line 39, in forward
vect, _ = self.encode(batch['lbls'])
File "/DATA/rani1/scratch/XC/programs/CafeXC/xc/method/mufin/network.py", line 34, in encode
return self.item_encoder(batch, pool=pool, output_attn_wts=output_attn_wts)
File "/DATA/rani1/miniconda3/envs/xc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/DATA/rani1/scratch/XC/programs/CafeXC/xc/libs/dataparallel.py", line 55, in forward
outputs = self.parallel_apply(self._replicas, inputs, kwargs)
File "/DATA/rani1/miniconda3/envs/xc/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
File "/DATA/rani1/miniconda3/envs/xc/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
output.reraise()
File "/DATA/rani1/miniconda3/envs/xc/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
File "/DATA/rani1/miniconda3/envs/xc/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
output = module(*input, **kwargs)
File "/DATA/rani1/miniconda3/envs/xc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/DATA/rani1/scratch/XC/programs/CafeXC/xc/method/mufin/models_encoders.py", line 77, in forward
content = super().forward(batch)
File "/DATA/rani1/scratch/XC/programs/CafeXC/xc/method/mufin/models_encoders.py", line 35, in forward
vect, mask = self.img_encoder(batch['img'].get_raw_vect())
File "/DATA/rani1/miniconda3/envs/xc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/DATA/rani1/scratch/XC/programs/CafeXC/xc/models/models_img.py", line 97, in forward
images = self.encode(images)
File "/DATA/rani1/scratch/XC/programs/CafeXC/xc/models/models_img.py", line 220, in encode
images = self.features(images,images, interpolate_pos_encoding=True)
File "/DATA/rani1/miniconda3/envs/xc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/DATA/rani1/miniconda3/envs/xc/lib/python3.6/site-packages/transformers/models/vit/modeling_vit.py", line 572, in forward
pixel_values, bool_masked_pos=bool_masked_pos, interpolate_pos_encoding=interpolate_pos_encoding
File "/DATA/rani1/miniconda3/envs/xc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/DATA/rani1/miniconda3/envs/xc/lib/python3.6/site-packages/transformers/models/vit/modeling_vit.py", line 138, in forward
mask_tokens = self.mask_token.expand(batch_size, seq_len, -1)
AttributeError: 'NoneType' object has no attribute 'expand'
`
