### ISSUE TITLE
No module named xc

### ISSUE THREAD

**Issue by suvanbalu** [Extreme-classification/MUFIN#5]
While running the final script 
`./run_MUFIN.sh 0,1 PreTrainedMufinMultiModal MM-AmazonTitles-300K MUFIN_pretrained ViT sentencebert -1 0`

I got an error stating that there is no package named **xc**, my pwd is `/home/scratch/XC/programs/MUFIN`

So I had to manually xc folder from `/programs/CafeXC` to my current working directory, and then the error was resolved. I'm not sure that was the correct step. So please look into it. 

The path for the xc folder could be added in the Python script using the sys package.

**Comment by anshumitts** [comment]
Hi @suvanbalu We want to avoid hard coded things as much as follows. I have fixed the bash script though. Thanks for using our work
